name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete 'nightly' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: server-nightly
          cut-off: A week ago UTC
          account-type: org
          org-name: get-shoppi
          keep-at-least: 0
          untagged-only: false
          token: ${{ secrets.PAT }}
